language: objective-c
cache:
  directories:
  - build
  - vendor
jobs:
  include:
  - stage: build
    osx_image: xcode12u
    install:
    - bundle install --path=vendor/bundle --binstubs=vendor/bin
    script:
    - bundle exec rake build-for-testing:simulator
  - &test
    stage: 'test (xcode12u)'
    osx_image: xcode12u
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone SE,OS=14.0']"
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 8,OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 8 Plus,OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 11,OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 11 Pro,OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 11 Pro Max,OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (11-inch) (2nd generation),OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch) (4th generation),OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (9.7-inch),OS=14.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad (8th generation),OS=14.0']" TESTCASE='MergedCellTests'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad (8th generation),OS=14.0']" TESTCASE='ScrollTests/testTableViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad (8th generation),OS=14.0']" TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad (8th generation),OS=14.0']" TESTCASE='ScrollTests/testRowHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad (8th generation),OS=14.0']" TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad (8th generation),OS=14.0']" TESTCASE='ScrollTests/testCircularScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad (8th generation),OS=14.0']" TESTCASE='SelectionTests'
  - stage: 'test (xcode11.6)'
    osx_image: xcode11.6
    script:
    - bundle exec rake test:simulator DESTINATIONS="['name=iPhone 8,OS=13.0']"
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - stage: carthage
    osx_image: xcode9
    script:
    - carthage build --no-skip-current
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
branches:
  only:
  - master
skip_cleanup: true
