language: objective-c
cache:
  directories:
  - build
  - vendor
jobs:
  include:
  - stage: build
    osx_image: xcode10.2
    install:
    - bundle install --path=vendor/bundle --binstubs=vendor/bin
    script:
    - bundle exec rake build-for-testing:simulator
  - &test
    stage: 'test'
    osx_image: xcode10.2
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone XÊ€,OS=12.2']"
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 5,OS=10.3.1']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 6s,OS=11.4', 'name=iPhone 7 Plus,OS=11.4']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Air 2,OS=11.4']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (9.7-inch),OS=11.4']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.4']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 5s,OS=12.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 6s,OS=11.4']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 6s Plus,OS=12.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 7,OS=12.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone X,OS=12.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone XS,OS=12.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone XS Max,OS=12.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=12.0']"
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=11.4']" TESTCASE='MergedCellTests'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=11.4']" TESTCASE='ScrollTests/testTableViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=11.4']" TESTCASE='ScrollTests/testColumnHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=11.4']" TESTCASE='ScrollTests/testRowHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=11.4']" TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=11.4']" TESTCASE='ScrollTests/testCircularScrolling'
  - <<: *test
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=11.4']" TESTCASE='SelectionTests'
  - &test94
    stage: 'test (xcode10.1)'
    osx_image: xcode10.1
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 4s,OS=9.3']" SWIFT_VERSION=4.1
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 5,OS=9.3']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 6s,OS=10.3.1', 'name=iPhone 7 Plus,OS=10.3.1']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Air 2,OS=10.3.1']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (9.7-inch),OS=10.3.1']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=10.3.1']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 6s Plus,OS=11.0']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPhone 7,OS=11.0']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad Pro (12.9-inch),OS=11.0']" SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=9.3']" TESTCASE='MergedCellTests' SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=9.3']" TESTCASE='ScrollTests/testTableViewScrolling' SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=9.3']" TESTCASE='ScrollTests/testColumnHeaderViewScrolling' SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=9.3']" TESTCASE='ScrollTests/testRowHeaderViewScrolling' SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=9.3']" TESTCASE='ScrollTests/testColumnAndRowHeaderViewScrolling' SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=9.3']" TESTCASE='ScrollTests/testCircularScrolling' SWIFT_VERSION=4.1
  - <<: *test94
    script:
    - bundle exec rake test-without-building:simulator
      DESTINATIONS="['name=iPad 2,OS=9.3']" TESTCASE='SelectionTests' SWIFT_VERSION=4.1
  - stage: 'test (xcode8.3)'
    osx_image: xcode8.3
    script:
    - bundle exec rake test:simulator DESTINATIONS="['name=iPhone 4s,OS=9.3']" SWIFT_VERSION=3.0
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - stage: 'test (xcode8.3)'
    osx_image: xcode8.3
    script:
    - bundle exec rake test:simulator DESTINATIONS="['name=iPhone 7,OS=10.3.1']" SWIFT_VERSION=3.0
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f 'coverage.txt'
  - stage: carthage
    osx_image: xcode10
    script:
    - echo SWIFT_VERSION=\"4.2\" > swift.xcconfig
    - XCODE_XCCONFIG_FILE=`pwd`/swift.xcconfig carthage build --no-skip-current
  - stage: carthage
    osx_image: xcode9.4
    script:
    - echo SWIFT_VERSION=\"4.1\" > swift.xcconfig
    - XCODE_XCCONFIG_FILE=`pwd`/swift.xcconfig carthage build --no-skip-current
  - stage: carthage
    osx_image: xcode8.3
    script:
    - echo SWIFT_VERSION=\"3.0\" > swift.xcconfig
    - XCODE_XCCONFIG_FILE=`pwd`/swift.xcconfig carthage build --no-skip-current
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
branches:
  only:
  - master
skip_cleanup: true
